### ISSUE TITLE
Feature request: add posibility to have only one volume mounted

### ISSUE THREAD

**Issue by ciotorcristian** [raydak-labs/configarr#117]
Hello,

I would like to have the posibility to only have to mount one volume to /app and the three needed directories will be created automatically there. I am using portainer and configure docker volumes so it would be easier to just create one volume per container.

**Comment by BlackDark** [comment]
Hi @ciotorcristian i have implemented something.
You can test it with following image (not released yet as a new version) `ghcr.io/raydak-labs/configarr:main@sha256:4612d94f83f194f24f886286ec54dce4768d908e831c9fc344b95dcb048a1dd8`

Here are the required settings: https://cf59cb88.configarr-preview.pages.dev/docs/configuration/environment-variables#examples
