### ISSUE TITLE
Add scheduler for docker compose

### ISSUE THREAD

**Issue by ciotorcristian** [raydak-labs/configarr#123]
Hello,

I encountered an issue while running Configarr. When I set the restart policy in Docker Compose to "no," the container runs and exits after completing a single sync. However, if I set the restart policy to "unless-stopped," the container runs indefinitely, causing it to restart and sync repeatedly. Is there a possibility to add a feature similar to Recyclarr, where I can configure an environment variable to schedule the container to run hourly or daily?

Thanks

**Comment by BlackDark** [comment]
Hi @ciotorcristian 
for now I am not planning to add direct support for scheduling things inside the container.
But i provided examples of how you can achieve what you want with schedulers which run the container regulray.
Here you can take a quick look if this does help you and is sufficient: https://github.com/raydak-labs/configarr/tree/docs/scheduler/examples/scheduled

**Comment by ciotorcristian** [comment]
Hi, thanks for the support. I will take a look over the documentation and try to implement it. I will update you if I succeed.

**Comment by BlackDark** [comment]
Closing for now. If we see a bigger need for internal scheduling capabilities instead of managing those with external solutions we can think about doing something.

@ciotorcristian if you need further help feel free to reach out :)
