### ISSUE TITLE
Provide how to

### ISSUE THREAD

**Issue by chrisb86** [raydak-labs/configarr#59]
I'm pretty new to Sonarr and Radarr and tried to implement the PCJones settings by myself before. I think your project looks promising but a struggle to set it up.

I can ran the full example stack and it works so far. But I don't get how I can customize the config to implement the provided german custom formats.

Could you perhaps post your config somewhere?

For me the README is more confusing than it helps right now.

**Comment by BlackDark** [comment]
Provided an updated docs here: https://github.com/raydak-labs/configarr/blob/docs/update/README.md

Does it help?
