### ISSUE TITLE
Issues Starting Configarr

### ISSUE THREAD

**Issue by m4tz3** [raydak-labs/configarr#79]
Slowly I'm starting to think I'm incapable.
I have Radarr, Sonarr, and Gluetun running without any issues.
But I'm struggling with Configarr.

I’ve created the config, secrets, and my docker-compose.yml.
In the config, I made the necessary adjustment regarding 'assign_scores_to'.
However, I can't get Configarr to start.

Could someone help me with debugging this?

```
<html><body>
<!--StartFragment-->
date | stream | content
-- | -- | --
2024/10/05 08:21:49 | stdout | ELIFECYCLE  Command failed with exit code 1.
2024/10/05 08:21:49 | stderr | Node.js v22.7.0
2024/10/05 08:21:49 | stderr |  
2024/10/05 08:21:49 | stderr | at async run (/app/index.ts:288:5)
2024/10/05 08:21:49 | stderr | at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2024/10/05 08:21:49 | stderr | at configureSonarrApi (/app/src/api.ts:70:11)
2024/10/05 08:21:49 | stderr | Error
2024/10/05 08:21:49 | stderr |  
2024/10/05 08:21:49 | stderr |  
2024/10/05 08:21:49 | stderr | ^
2024/10/05 08:21:49 | stderr | throw new Error(message);
2024/10/05 08:21:49 | stderr | /app/src/api.ts:70
2024/10/05 08:21:49 | stdout | }
2024/10/05 08:21:49 | stdout | "statusCode": null
2024/10/05 08:21:49 | stdout | res: {
2024/10/05 08:21:49 | stdout | [06:21:49.259] [31mERROR[39m (35):
2024/10/05 08:21:49 | stdout | [06:21:49.160] [32mINFO[39m (35): [36mProcessing Sonarr Instance: instance1[39m
2024/10/05 08:21:49 | stdout | [06:21:49.152] [32mINFO[39m (35):
2024/10/05 08:21:49 | stdout | [06:21:49.152] [32mINFO[39m (35): [36m#############################################[39m
2024/10/05 08:21:49 | stdout | [06:21:49.152] [32mINFO[39m (35): [36m### Processing Sonarr ...[39m
2024/10/05 08:21:49 | stdout | [06:21:49.152] [32mINFO[39m (35): [36m#############################################[39m
2024/10/05 08:21:49 | stdout | [06:21:49.152] [32mINFO[39m (35):
2024/10/05 08:21:49 | stdout | [06:21:49.151] [32mINFO[39m (35): [36mTrashGuide repo on 'master'[39m
2024/10/05 08:21:49 | stdout | [06:21:48.683] [32mINFO[39m (35): [36mChecking TrashGuide repo (/app/repos/trash-guides)[39m
2024/10/05 08:21:49 | stdout | [06:21:48.682] [32mINFO[39m (35): [36mRecyclarr repo on 'master'[39m
2024/10/05 08:21:48 | stdout | [06:21:47.979] [32mINFO[39m (35): [36mChecking Recyclarr repo (/app/repos/recyclarr-config)[39m
2024/10/05 08:21:45 | stdout |  
2024/10/05 08:21:45 | stdout | > tsx index.ts
2024/10/05 08:21:45 | stdout | > configarr@0.0.0 start /app
2024/10/05 08:21:45 | stdout |  

<!--EndFragment-->
</body>
</html>
```

**Comment by BlackDark** [comment]
Hi @m4tz3 can you provide your config?
Looks like the connection to sonarr does not work. Sadly no error message is provided. Maybe I can debug with your config and improve that.

On top of that maybe adding an option for users without color support in their terminal :D

**Comment by m4tz3** [comment]
Hi, thanks for the quick response. Admittedly, my Docker project has grown and become a bit tangled. I’m routing the services through Gluetun. I have Sabnzbd, Radarr, Prowlarr, and Sonarr running. Configarr, however, is giving me a hard time.

**My Docker Compose**
`version: "3.8"

services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "8775:8080"       # SABnzbd
      - "9696:9696"     # Prowlarr
      - "8005:8000"       # Gluetun HTTP Control Server port
      - "8989:8989"       # Sonarr
      - "7878:7878"       # Radarr
      - "5005:5005" 
      - "5006:5006" 
    volumes:
      - /volume3/docker/sonarrradarretc/gluetun/config:/gluetun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      # Wireguard:
      - WIREGUARD_ENDPOINT_IP=${WIREGUARD_ENDPOINT_IP}
      - WIREGUARD_ENDPOINT_PORT=${WIREGUARD_ENDPOINT_PORT}
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - TZ=${TZ}

    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - /volume3/docker/sonarrradarretc/sabnzbd/config:/config
      - /volume3/sabnzbd/complete:/downloads 
      - /volume3/sabnzbd/incomplete:/incomplete 
    network_mode: "service:gluetun"
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - /volume3/docker/sonarrradarretc/sonarr/config:/config
      - /volume1/Serien:/Serien
      - /volume1/tv:/tv
      - /volume3/sabnzbd/complete:/downloads
    network_mode: "service:gluetun"    
    depends_on:
      - sabnzbd
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - /volume3/docker/sonarrradarretc/radarr/config:/config
      - /volume1/movies:/movies
      - /volume3/sabnzbd/complete:/downloads
    network_mode: "service:gluetun"    
    depends_on:
      - sabnzbd
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - /volume3/docker/sonarrradarretc/prowlarr/config:/config
    network_mode: "service:gluetun"      
    restart: unless-stopped

  umlautadaptarr:
    image: pcjones/umlautadaptarr:latest
    container_name: umlautadaptarr
    environment:
      - TZ=Europe/Berlin
      - SONARR__ENABLED=true
      - SONARR__HOST=http://localhost:8989
      - SONARR__APIKEY=${SONARR_APIKEY}
      - RADARR__ENABLED=true
      - RADARR__HOST=http://localhost:7878
      - RADARR__APIKEY=${RADARR_APIKEY}
    network_mode: "service:gluetun"    
    depends_on:
      - sonarr
      - radarr
    restart: unless-stopped

  configarr:
    image: ghcr.io/raydak-labs/configarr:opt-enhance-error-message
    container_name: configarr
    volumes:
      - /volume3/docker/sonarrradarretc/configarr/config:/app/config
      - /volume3/docker/sonarrradarretc/configarr/dockerrepos:/app/repos
      - /volume3/docker/sonarrradarretc/configarr/custom/cfs:/app/cfs
      - /volume3/docker/sonarrradarretc/configarr/custom/templates:/app/templates
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    restart: unless-stopped

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: "172.27.0.0/16"`

**My config.yml in /configarr/config:**
`trashGuideUrl: https://github.com/TRaSH-Guides/Guides
#trashRevision: master # Optional to specify sha
recyclarrConfigUrl: https://github.com/recyclarr/config-templates
#recyclarrRevision: master # Optional to specify sha

# Optional if you want to add custom formats locally
#localCustomFormatsPath: ./custom/cfs
#localConfigTemplatesPath: /app/templates

sonarr:
  series:
    # Set the URL/API Key to your actual instance
    base_url: http://localhost:8989
    api_key: !secret SONARR_API_KEY

    # Quality definitions from the guide to sync to Sonarr. Choices: series, anime
    quality_definition:
      type: series

    include:
      # Comment out any of the following includes to disable them
      #### WEB-1080p
      - template: sonarr-quality-definition-series
      - template: sonarr-v4-quality-profile-web-1080p
      - template: sonarr-v4-custom-formats-web-1080p

      #### WEB-2160p
      - template: sonarr-v4-quality-profile-web-2160p
      - template: sonarr-v4-custom-formats-web-2160p

    # Custom Formats: https://recyclarr.dev/wiki/yaml/config-reference/custom-formats/
    custom_formats: []

radarr:
  instance1:
    define: true`

**My log out of the container manager (using a synology nas):**
`configarr
date,stream,content
2024/10/06 09:54:22,stdout, ELIFECYCLE  Command failed with exit code 1.

2024/10/06 09:54:22,stderr,Node.js v22.9.0

2024/10/06 09:54:22,stderr,

2024/10/06 09:54:22,stderr,    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)

2024/10/06 09:54:22,stderr,    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:483:26)

2024/10/06 09:54:22,stderr,    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)

2024/10/06 09:54:22,stderr,    at <anonymous> (/app/index.ts:322:1)

2024/10/06 09:54:22,stderr,    at run (/app/index.ts:276:29)

2024/10/06 09:54:22,stderr,    at getConfig (/app/src/config.ts:52:12)

2024/10/06 09:54:22,stderr,    at transformConfig (/app/src/config.ts:106:13)

2024/10/06 09:54:22,stderr,    at mappedCustomFormats (/app/src/config.ts:75:37)

2024/10/06 09:54:22,stderr,    at Array.reduce (<anonymous>)

2024/10/06 09:54:22,stderr,    at <anonymous> (/app/src/config.ts:77:58)

2024/10/06 09:54:22,stderr,TypeError: Cannot read properties of undefined (reading 'map')

2024/10/06 09:54:22,stderr,

2024/10/06 09:54:22,stderr,

2024/10/06 09:54:22,stderr,                                                         ^

2024/10/06 09:54:22,stderr,        const mappedCustomFormats = value.custom_formats.map<ConfigCustomFormat>((cf) => {

2024/10/06 09:54:22,stderr,/app/src/config.ts:77

2024/10/06 09:54:21,stdout,

2024/10/06 09:54:21,stdout,> tsx index.ts

2024/10/06 09:54:21,stdout,> configarr@0.0.0 start /app

2024/10/06 09:54:21,stdout,

2024/10/06 09:53:53,stdout, ELIFECYCLE  Command failed with exit code 1.

2024/10/06 09:53:53,stderr,Node.js v22.9.0

2024/10/06 09:53:53,stderr,

2024/10/06 09:53:53,stderr,    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)

2024/10/06 09:53:53,stderr,    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:483:26)

2024/10/06 09:53:53,stderr,    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)

2024/10/06 09:53:53,stderr,    at <anonymous> (/app/index.ts:322:1)

2024/10/06 09:53:53,stderr,    at run (/app/index.ts:276:29)

2024/10/06 09:53:53,stderr,    at getConfig (/app/src/config.ts:52:12)

2024/10/06 09:53:53,stderr,    at transformConfig (/app/src/config.ts:106:13)

2024/10/06 09:53:53,stderr,    at mappedCustomFormats (/app/src/config.ts:75:37)

2024/10/06 09:53:53,stderr,    at Array.reduce (<anonymous>)

2024/10/06 09:53:53,stderr,    at <anonymous> (/app/src/config.ts:77:58)

2024/10/06 09:53:53,stderr,TypeError: Cannot read properties of undefined (reading 'map')

2024/10/06 09:53:53,stderr,

2024/10/06 09:53:53,stderr,

2024/10/06 09:53:53,stderr,                                                         ^

2024/10/06 09:53:53,stderr,        const mappedCustomFormats = value.custom_formats.map<ConfigCustomFormat>((cf) => {

2024/10/06 09:53:53,stderr,/app/src/config.ts:77

2024/10/06 09:53:52,stdout,

2024/10/06 09:53:52,stdout,> tsx index.ts

2024/10/06 09:53:52,stdout,> configarr@0.0.0 start /app

2024/10/06 09:53:52,stdout,

2024/10/06 09:53:37,stdout, ELIFECYCLE  Command failed with exit code 1.

2024/10/06 09:53:37,stderr,Node.js v22.9.0

2024/10/06 09:53:37,stderr,

2024/10/06 09:53:37,stderr,    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)

2024/10/06 09:53:37,stderr,    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:483:26)

2024/10/06 09:53:37,stderr,    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)

2024/10/06 09:53:37,stderr,    at <anonymous> (/app/index.ts:322:1)

2024/10/06 09:53:37,stderr,    at run (/app/index.ts:276:29)

2024/10/06 09:53:37,stderr,    at getConfig (/app/src/config.ts:52:12)

2024/10/06 09:53:37,stderr,    at transformConfig (/app/src/config.ts:106:13)

2024/10/06 09:53:37,stderr,    at mappedCustomFormats (/app/src/config.ts:75:37)

2024/10/06 09:53:37,stderr,    at Array.reduce (<anonymous>)

2024/10/06 09:53:37,stderr,    at <anonymous> (/app/src/config.ts:77:58)

2024/10/06 09:53:37,stderr,TypeError: Cannot read properties of undefined (reading 'map')

2024/10/06 09:53:37,stderr,

2024/10/06 09:53:37,stderr,

2024/10/06 09:53:37,stderr,                                                         ^

2024/10/06 09:53:37,stderr,        const mappedCustomFormats = value.custom_formats.map<ConfigCustomFormat>((cf) => {

2024/10/06 09:53:37,stderr,/app/src/config.ts:77

2024/10/06 09:53:36,stdout,

2024/10/06 09:53:36,stdout,> tsx index.ts

2024/10/06 09:53:36,stdout,> configarr@0.0.0 start /app

2024/10/06 09:53:36,stdout,

2024/10/06 09:53:27,stdout, ELIFECYCLE  Command failed with exit code 1.

2024/10/06 09:53:27,stderr,Node.js v22.9.0

2024/10/06 09:53:27,stderr,

2024/10/06 09:53:27,stderr,    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)

2024/10/06 09:53:27,stderr,    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:483:26)

2024/10/06 09:53:27,stderr,    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)

2024/10/06 09:53:27,stderr,    at <anonymous> (/app/index.ts:322:1)

2024/10/06 09:53:27,stderr,    at run (/app/index.ts:276:29)

2024/10/06 09:53:27,stderr,    at getConfig (/app/src/config.ts:52:12)

2024/10/06 09:53:27,stderr,    at transformConfig (/app/src/config.ts:106:13)

2024/10/06 09:53:27,stderr,    at mappedCustomFormats (/app/src/config.ts:75:37)

2024/10/06 09:53:27,stderr,    at Array.reduce (<anonymous>)

2024/10/06 09:53:27,stderr,    at <anonymous> (/app/src/config.ts:77:58)

2024/10/06 09:53:27,stderr,TypeError: Cannot read properties of undefined (reading 'map')

2024/10/06 09:53:27,stderr,

2024/10/06 09:53:27,stderr,

2024/10/06 09:53:27,stderr,                                                         ^

2024/10/06 09:53:27,stderr,        const mappedCustomFormats = value.custom_formats.map<ConfigCustomFormat>((cf) => {

2024/10/06 09:53:27,stderr,/app/src/config.ts:77

2024/10/06 09:53:26,stdout,

2024/10/06 09:53:26,stdout,> tsx index.ts

2024/10/06 09:53:26,stdout,> configarr@0.0.0 start /app

2024/10/06 09:53:26,stdout,

2024/10/06 09:53:21,stdout, ELIFECYCLE  Command failed with exit code 1.

2024/10/06 09:53:21,stderr,Node.js v22.9.0

2024/10/06 09:53:21,stderr,

2024/10/06 09:53:21,stderr,    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)

2024/10/06 09:53:21,stderr,    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:483:26)

2024/10/06 09:53:21,stderr,    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)

2024/10/06 09:53:21,stderr,    at <anonymous> (/app/index.ts:322:1)

2024/10/06 09:53:21,stderr,    at run (/app/index.ts:276:29)

2024/10/06 09:53:21,stderr,    at getConfig (/app/src/config.ts:52:12)

2024/10/06 09:53:21,stderr,    at transformConfig (/app/src/config.ts:106:13)

2024/10/06 09:53:21,stderr,    at mappedCustomFormats (/app/src/config.ts:75:37)

2024/10/06 09:53:21,stderr,    at Array.reduce (<anonymous>)

2024/10/06 09:53:21,stderr,    at <anonymous> (/app/src/config.ts:77:58)

2024/10/06 09:53:21,stderr,TypeError: Cannot read properties of undefined (reading 'map')

2024/10/06 09:53:21,stderr,

2024/10/06 09:53:21,stderr,

2024/10/06 09:53:21,stderr,                                                         ^

2024/10/06 09:53:21,stderr,        const mappedCustomFormats = value.custom_formats.map<ConfigCustomFormat>((cf) => {

2024/10/06 09:53:21,stderr,/app/src/config.ts:77

2024/10/06 09:53:19,stdout,

2024/10/06 09:53:19,stdout,> tsx index.ts

2024/10/06 09:53:19,stdout,> configarr@0.0.0 start /app

2024/10/06 09:53:19,stdout,

2024/10/06 09:53:16,stdout, ELIFECYCLE  Command failed with exit code 1.

2024/10/06 09:53:16,stderr,Node.js v22.9.0

2024/10/06 09:53:16,stderr,

2024/10/06 09:53:16,stderr,    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)

2024/10/06 09:53:16,stderr,    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:483:26)

2024/10/06 09:53:16,stderr,    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)

2024/10/06 09:53:16,stderr,    at <anonymous> (/app/index.ts:322:1)

2024/10/06 09:53:16,stderr,    at run (/app/index.ts:276:29)

2024/10/06 09:53:16,stderr,    at getConfig (/app/src/config.ts:52:12)

2024/10/06 09:53:16,stderr,    at transformConfig (/app/src/config.ts:106:13)

2024/10/06 09:53:16,stderr,    at mappedCustomFormats (/app/src/config.ts:75:37)

2024/10/06 09:53:16,stderr,    at Array.reduce (<anonymous>)

2024/10/06 09:53:16,stderr,    at <anonymous> (/app/src/config.ts:77:58)

2024/10/06 09:53:16,stderr,TypeError: Cannot read properties of undefined (reading 'map')

2024/10/06 09:53:16,stderr,

2024/10/06 09:53:16,stderr,

2024/10/06 09:53:16,stderr,                                                         ^

2024/10/06 09:53:16,stderr,        const mappedCustomFormats = value.custom_formats.map<ConfigCustomFormat>((cf) => {

2024/10/06 09:53:16,stderr,/app/src/config.ts:77

2024/10/06 09:53:15,stdout,

2024/10/06 09:53:15,stdout,> tsx index.ts

2024/10/06 09:53:15,stdout,> configarr@0.0.0 start /app

2024/10/06 09:53:15,stdout,

2024/10/06 09:53:11,stdout, ELIFECYCLE  Command failed with exit code 1.

2024/10/06 09:53:11,stderr,Node.js v22.9.0

2024/10/06 09:53:11,stderr,

2024/10/06 09:53:11,stderr,    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)

2024/10/06 09:53:11,stderr,    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:483:26)

2024/10/06 09:53:11,stderr,    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)

2024/10/06 09:53:11,stderr,    at <anonymous> (/app/index.ts:322:1)

2024/10/06 09:53:11,stderr,    at run (/app/index.ts:276:29)

2024/10/06 09:53:11,stderr,    at getConfig (/app/src/config.ts:52:12)

2024/10/06 09:53:11,stderr,    at transformConfig (/app/src/config.ts:106:13)

2024/10/06 09:53:11,stderr,    at mappedCustomFormats (/app/src/config.ts:75:37)

2024/10/06 09:53:11,stderr,    at Array.reduce (<anonymous>)

2024/10/06 09:53:11,stderr,    at <anonymous> (/app/src/config.ts:77:58)

2024/10/06 09:53:11,stderr,TypeError: Cannot read properties of undefined (reading 'map')

2024/10/06 09:53:11,stderr,

2024/10/06 09:53:11,stderr,

2024/10/06 09:53:11,stderr,                                                         ^

2024/10/06 09:53:11,stderr,        const mappedCustomFormats = value.custom_formats.map<ConfigCustomFormat>((cf) => {

2024/10/06 09:53:11,stderr,/app/src/config.ts:77

2024/10/06 09:53:07,stdout,

2024/10/06 09:53:07,stdout,> tsx index.ts

2024/10/06 09:53:07,stdout,> configarr@0.0.0 start /app

2024/10/06 09:53:07,stdout,

2024/10/06 09:53:03,stdout, ELIFECYCLE  Command failed with exit code 1.

2024/10/06 09:53:03,stderr,Node.js v22.9.0

2024/10/06 09:53:03,stderr,

2024/10/06 09:53:03,stderr,    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)

2024/10/06 09:53:03,stderr,    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:483:26)

2024/10/06 09:53:03,stderr,    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)

2024/10/06 09:53:03,stderr,    at <anonymous> (/app/index.ts:322:1)

2024/10/06 09:53:03,stderr,    at run (/app/index.ts:276:29)

2024/10/06 09:53:03,stderr,    at getConfig (/app/src/config.ts:52:12)

2024/10/06 09:53:03,stderr,    at transformConfig (/app/src/config.ts:106:13)

2024/10/06 09:53:03,stderr,    at mappedCustomFormats (/app/src/config.ts:75:37)

2024/10/06 09:53:03,stderr,    at Array.reduce (<anonymous>)

2024/10/06 09:53:03,stderr,    at <anonymous> (/app/src/config.ts:77:58)

2024/10/06 09:53:03,stderr,TypeError: Cannot read properties of undefined (reading 'map')

2024/10/06 09:53:03,stderr,

2024/10/06 09:53:03,stderr,

2024/10/06 09:53:03,stderr,                                                         ^

2024/10/06 09:53:03,stderr,        const mappedCustomFormats = value.custom_formats.map<ConfigCustomFormat>((cf) => {

2024/10/06 09:53:03,stderr,/app/src/config.ts:77

2024/10/06 09:52:59,stdout,

2024/10/06 09:52:59,stdout,> tsx index.ts

2024/10/06 09:52:59,stdout,> configarr@0.0.0 start /app

2024/10/06 09:52:59,stdout,

2024/10/06 09:52:56,stdout, ELIFECYCLE  Command failed with exit code 1.

2024/10/06 09:52:56,stderr,Node.js v22.9.0

2024/10/06 09:52:56,stderr,

2024/10/06 09:52:56,stderr,    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)

2024/10/06 09:52:56,stderr,    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:483:26)

2024/10/06 09:52:56,stderr,    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)

2024/10/06 09:52:56,stderr,    at <anonymous> (/app/index.ts:322:1)

2024/10/06 09:52:56,stderr,    at run (/app/index.ts:276:29)

2024/10/06 09:52:56,stderr,    at getConfig (/app/src/config.ts:52:12)

2024/10/06 09:52:56,stderr,    at transformConfig (/app/src/config.ts:106:13)

2024/10/06 09:52:56,stderr,    at mappedCustomFormats (/app/src/config.ts:75:37)

2024/10/06 09:52:56,stderr,    at Array.reduce (<anonymous>)

2024/10/06 09:52:56,stderr,    at <anonymous> (/app/src/config.ts:77:58)

2024/10/06 09:52:56,stderr,TypeError: Cannot read properties of undefined (reading 'map')

2024/10/06 09:52:56,stderr,

2024/10/06 09:52:56,stderr,

2024/10/06 09:52:56,stderr,                                                         ^

2024/10/06 09:52:56,stderr,        const mappedCustomFormats = value.custom_formats.map<ConfigCustomFormat>((cf) => {

2024/10/06 09:52:56,stderr,/app/src/config.ts:77

2024/10/06 09:52:53,stdout,

2024/10/06 09:52:53,stdout,> tsx index.ts

2024/10/06 09:52:53,stdout,> configarr@0.0.0 start /app

2024/10/06 09:52:53,stdout,

2024/10/06 09:52:49,stdout, ELIFECYCLE  Command failed with exit code 1.

2024/10/06 09:52:49,stderr,Node.js v22.9.0

2024/10/06 09:52:49,stderr,

2024/10/06 09:52:49,stderr,    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)

2024/10/06 09:52:49,stderr,    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:483:26)

2024/10/06 09:52:49,stderr,    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)

2024/10/06 09:52:49,stderr,    at <anonymous> (/app/index.ts:322:1)

2024/10/06 09:52:49,stderr,    at run (/app/index.ts:276:29)

2024/10/06 09:52:49,stderr,    at getConfig (/app/src/config.ts:52:12)

2024/10/06 09:52:49,stderr,    at transformConfig (/app/src/config.ts:106:13)

2024/10/06 09:52:49,stderr,    at mappedCustomFormats (/app/src/config.ts:75:37)

2024/10/06 09:52:49,stderr,    at Array.reduce (<anonymous>)

2024/10/06 09:52:49,stderr,    at <anonymous> (/app/src/config.ts:77:58)

2024/10/06 09:52:49,stderr,TypeError: Cannot read properties of undefined (reading 'map')

2024/10/06 09:52:49,stderr,

2024/10/06 09:52:49,stderr,

2024/10/06 09:52:49,stderr,                                                         ^

2024/10/06 09:52:49,stderr,        const mappedCustomFormats = value.custom_formats.map<ConfigCustomFormat>((cf) => {

2024/10/06 09:52:49,stderr,/app/src/config.ts:77

2024/10/06 09:52:41,stdout,

2024/10/06 09:52:41,stdout,> tsx index.ts

2024/10/06 09:52:41,stdout,> configarr@0.0.0 start /app

2024/10/06 09:52:41,stdout,

`

**Comment by BlackDark** [comment]
Allright 2 things i noticed:
- `base_url` for the API probably will not work because localhost in the container is the container itself. In your case this should be `http://sonarr:8989` (as everything is one docker-compose services can access each other)
- we have currently not implemented config/yaml validation so we get this weird error. Try setting radarr in the config to `radarr: {}`

See

```yaml
trashGuideUrl: https://github.com/TRaSH-Guides/Guides
#trashRevision: master # Optional to specify sha
recyclarrConfigUrl: https://github.com/recyclarr/config-templates
#recyclarrRevision: master # Optional to specify sha

# Optional if you want to add custom formats locally
#localCustomFormatsPath: ./custom/cfs
#localConfigTemplatesPath: /app/templates

sonarr:
  series:
    # Set the URL/API Key to your actual instance
    base_url: http://localhost:8989
    api_key: !secret SONARR_API_KEY

    # Quality definitions from the guide to sync to Sonarr. Choices: series, anime
    quality_definition:
      type: series

    include:
      # Comment out any of the following includes to disable them
      #### WEB-1080p
      - template: sonarr-quality-definition-series
      - template: sonarr-v4-quality-profile-web-1080p
      - template: sonarr-v4-custom-formats-web-1080p

      #### WEB-2160p
      - template: sonarr-v4-quality-profile-web-2160p
      - template: sonarr-v4-custom-formats-web-2160p

    # Custom Formats: https://recyclarr.dev/wiki/yaml/config-reference/custom-formats/
    custom_formats: []

radarr: {}
```

**Comment by m4tz3** [comment]
I have adjusted the config.yml. Unfortunately, that didn't help either. I'll keep trying. Thanks in advance for the first tip.

[configarr(2).csv](https://github.com/user-attachments/files/17274309/configarr.2.csv)

**Comment by BlackDark** [comment]
Now we have a permission problem. I have update the image (maybe you have to pull it again or set pullPolicy to always). If it does not work remove it from the dockerfile and pull/delete the image by hand on your NAS.

The env vars `PUID/PGID` are linuxserver env vars and we do nto support them. But you can use the default `user` field in the compose to change the running user. 

Try this:

```yaml

version: "3.8"

services:
  configarr:
    image: ghcr.io/raydak-labs/configarr:opt-enhance-error-message
    pull_policy: always # new for now can be removed after testing
    user: ${PUID}:${PGID} # official syntax
    container_name: configarr
    volumes:
      - /volume3/docker/sonarrradarretc/configarr/config:/app/config
      - /volume3/docker/sonarrradarretc/configarr/dockerrepos:/app/repos
      - /volume3/docker/sonarrradarretc/configarr/custom/cfs:/app/cfs
      - /volume3/docker/sonarrradarretc/configarr/custom/templates:/app/templates
    environment:
      - TZ=${TZ}
    restart: unless-stopped
 ```

**Comment by BlackDark** [comment]
@m4tz3 hopefully with the updated docs and new version your problem is fixed? If not feel free to reopen the issue :)
