### ISSUE TITLE
Radarr version

### ISSUE THREAD

**Issue by ciotorcristian** [raydak-labs/configarr#87]
Checking the README it is stated that the project only supports Sonarr v4 and radarr v4. Is there any issue with radarr v5, the latest versions? Will this not work with radarr?

**Comment by BlackDark** [comment]
Ah, sorry typo. Of course radarr v5 :)

**Comment by jarama** [comment]
Sorry to reopen this old issue, but I figured it is the best place to ask.

Given that the newest version of radarr is now v6 instead of v5, does configarr support radarr v6 already? I’ve held off updating radarr because I rely on configarr so much.

**Comment by BlackDark** [comment]
Hi @jarama , i have it running without noticable problems. So it is save for v6 also :)

**Comment by jarama** [comment]
> Hi [@jarama](https://github.com/jarama) , i have it running without noticable problems. So it is save for v6 also :)

Perfect, thanks! Maybe this should then be updated on GitHub and the wiki, because it currently says quite front-and-center that only radarr v5 is supported.

**Comment by BlackDark** [comment]
> > Hi [@jarama](https://github.com/jarama) , i have it running without noticable problems. So it is save for v6 also :)
> 
> Perfect, thanks! Maybe this should then be updated on GitHub and the wiki, because it currently says quite front-and-center that only radarr v5 is supported.

Yep, updated README and docs to show v5+
