### ISSUE TITLE
MinUpgradeFormatScore must be greater than or equal to 1

### ISSUE THREAD

**Issue by stefan-fast** [raydak-labs/configarr#88]
Hello,

I just tried using configarr and it runs into an error while creating Quality Profiles. I used the Kubernetes cronjob example in my cluster. My config is identical to that of the example in the README:
```
config.yml: |
    trashGuideUrl: https://github.com/TRaSH-Guides/Guides
    recyclarrConfigUrl: https://github.com/recyclarr/config-templates

    sonarr:
      series:
        # Set the URL/API Key to your actual instance
        base_url: http://sonarr:8989
        api_key: !secret SONARR_API_KEY

        # Quality definitions from the guide to sync to Sonarr. Choices: series, anime
        quality_definition:
          type: series

        include:
          # Comment out any of the following includes to disable them
          #### WEB-1080p
          - template: sonarr-quality-definition-series
          - template: sonarr-v4-quality-profile-web-1080p
          - template: sonarr-v4-custom-formats-web-1080p

          #### WEB-2160p
          - template: sonarr-v4-quality-profile-web-2160p
          - template: sonarr-v4-custom-formats-web-2160p

        # Custom Formats: https://recyclarr.dev/wiki/yaml/config-reference/custom-formats/
        custom_formats: []
    radarr: {}
```

The error message is not really helping in this case since `error.response.data` seems to be `undefined`:
```
INFO  [19:00:02.368]: Checking Recyclarr repo (/app/repos/recyclarr-config)
INFO  [19:00:02.704]: Recyclarr repo on 'master'
INFO  [19:00:02.705]: Checking TrashGuide repo (/app/repos/trash-guides)
INFO  [19:00:03.227]: TrashGuide repo on 'master'
INFO  [19:00:03.227]: 
INFO  [19:00:03.228]: #############################################
INFO  [19:00:03.228]: ### Processing Sonarr ...
INFO  [19:00:03.228]: #############################################
INFO  [19:00:03.228]: 
INFO  [19:00:03.229]: Processing Sonarr Instance: series
INFO  [19:00:03.281]: Recyclarr includes 5 templates
INFO  [19:00:03.287]: Trash CFs: 185
INFO  [19:00:03.297]: CustomFormats on server: 46
INFO  [19:00:03.298]: Created CFs: 0, Updated CFs: 0, Untouched CFs: 43, Error CFs: 0
INFO  [19:00:03.298]: CustomFormats synchronized
INFO  [19:00:03.302]: QualityDefinitions do not need update!
INFO  [19:00:03.313]: QualityProfile 'WEB-1080p' not found in server. Will be created.
INFO  [19:00:03.314]: QualityProfile 'WEB-2160p' not found in server. Will be created.
INFO  [19:00:03.315]: QualityProfiles: Create: 2, Update: 0, Unchanged: 0
INFO  [19:00:03.322]:
/app/index.js:34961
        throw new Error(message);
              ^

Error: Failed creating QualityProfile (WEB-1080p): Data undefined
    at pipeline (/app/index.js:34961:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async run (/app/index.js:34996:5)

Node.js v22.9.0
```

I  enabled the option `DEBUG_CREATE_FILES` by setting the environment variable to `true` and tried again to write the generated profiles to disk. I used them and tried to curl against the `POST /api/v3/qualityprofile` endpoint of Sonarr. I got a `HTTP/1.1 400 Bad Request` response with the following body:
```
[
  {
    "propertyName": "MinUpgradeFormatScore",
    "errorMessage": "\u0027Min Upgrade Format Score\u0027 must be greater than or equal to \u00271\u0027.",
    "attemptedValue": 0,
    "severity": "error",
    "errorCode": "GreaterThanOrEqualValidator",
    "formattedMessageArguments": [],
    "formattedMessagePlaceholderValues": {
      "comparisonValue": 1,
      "comparisonProperty": "",
      "propertyName": "Min Upgrade Format Score",
      "propertyValue": 0
    }
  }
]
```

I looked up the property and found out it is called `minUpgradeFormatScore` in the JSON. But, there is no field `minUpgradeFormatScore` in the generated JSON. That's why it is probably read as 0. Then, I edited the generated JSON and added `"minUpgradeFormatScore": 1` according to the error message and tried to curl again. This time I got a `HTTP/1.1 201 Created` response.

This is the first time I am playing around with Sonarr, therefore I'm not yet sure what exactly this does. It has been added to Sonarr very recently Sonarr/Sonarr/pull/7161 . Also I don't know if this is addressed correctly here or if this should be fixed upstream from where the configs come from.

Other than that, everything seems to be working. Thanks for this amazing tool!

**Comment by BlackDark** [comment]
Hey @stefan-fast, thanks for very detailed report 🥇 
Can reproduce the issue with the newest sonarr docker image.

Switched a while from slim node image to alpine which cause this missing details in case of errors I think. As you correctly wrote we should the error directly in the log outputs. Will investigate

**Comment by BlackDark** [comment]
So @stefan-fast please verify if you still have the problem with `1.3.0` if yes you can reopen the issue :)

**Comment by stefan-fast** [comment]
Hey @BlackDark , thanks for the quick fix! I can confirm that it works perfectly fine now :)
